version: '3.2'

services:
  server:
    build: 
      context: .
    image: event-sourcing_server
    env_file:
      - .env
    environment:
     - ENV=production
    command: go test ./... -coverprofile=coverage.out