version: 2
jobs:
  build_go:
    working_directory: /app
    docker:
      - image: ivanoffdan/docker-codebeat
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/server.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/server.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=server -t server .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/server.tar server
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/server.tar
      - run:
          name: Run tests and send coverage report to Codebeat
          command: |
            ./test.sh
workflows:
  version: 2
  build_and_test_go:
    jobs:
      - build_go