// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"

// RouterContext is an autogenerated mock type for the RouterContext type
type RouterContext struct {
	mock.Mock
}

// AbortWithStatusJSON provides a mock function with given fields: code, jsonObject
func (_m *RouterContext) AbortWithStatusJSON(code int, jsonObject interface{}) {
	_m.Called(code, jsonObject)
}

// JSON provides a mock function with given fields: code, obj
func (_m *RouterContext) JSON(code int, obj interface{}) {
	_m.Called(code, obj)
}
